# Generated by Django 2.1.5 on 2019-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='metakeywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(error_messages={'required': 'Поле контента не может быть пустым'}),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'required': 'Заголовок не должен быть пустым', 'unique': 'Такой заголовок уже существует'}, max_length=100, unique=True),
        ),
    ]
